---
application:
  name: "luffyrenamebot"
  project: "renamebot"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "renamebotsj"
  version: "8.0"
routers:
- name: "main-luffyrenamebot"
  routes:
  - application_name: "luffyrenamebot"
    paths:
    - "/*"
